# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackChoices',
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['movie', 'viewed_on', 'rating']},
        ),
    ]
