# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
